name: 报告缺陷
description: 提出charrue-el相关的缺陷
title: "[Bug] 请替换成合适的标题"
labels: ["bug"]
body:
  - type: input
    id: reproduce
    attributes:
      label: 重现链接
      description: 请提供一个尽可能精简的 codesandbox 或 GitHub 仓库的链接。
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 组件和版本
      description: 你正在使用的组件的版本是多少？（注意不是 package.json 里的版本，而是 node_modules 里实际安装的版本）
      placeholder: 如 @charrue/layout 4.16.13
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: 请提供一个傻瓜式的操作步骤，方便我们无脑重现问题。
      placeholder: |
        比如：
        1. 点击重现链接里的主按钮
        2. 等待五秒钟
        3. 观察按钮的边框
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
      placeholder: 比如：按钮样式正常，边框一直存在
    validations:
      required: true
  - type: textarea
    id: reality
    attributes:
      label: 实际的结果是什么？
      placeholder: 比如：按钮样式异常，边框突然丢失
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 浏览器
      description: 在哪些浏览器上能重现这个问题？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Internet Explorer
        - Others
  - type: input
    id: browsers-version
    attributes:
      label: 浏览器版本
      placeholder: 如：版本 95.0.4638.69（正式版本） (x86_64)
  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 使用的操作系统是？
      options:
        - Windows
        - MacOS
        - iOS
        - Android
        - Others
